version: '3.8'

services:
  server:
    build: ./server
    container_name: it-assets-server
    restart: always
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://user:password@db:5432/it_assets?schema=public
      - JWT_SECRET=supersecretkey
      - CLERK_SECRET_KEY=sk_live_uC0NW7YJxk7J4FxOoPSRcNVrc1JDB3Ak3M33qWXDwg
    ports:
      - "3000:3000"
    command: /bin/sh -c "npx prisma db push --accept-data-loss && node prisma/seed.js && node src/index.js"
    depends_on:
      - db
    volumes:
      - ./server/uploads:/app/uploads

  client:
    build:
      context: ./client
      args:
        - VITE_CLERK_PUBLISHABLE_KEY=pk_live_Y2xlcmsuZ3VjY2ktYmVsdC5tZSQ
    container_name: it-assets-client
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - server
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    container_name: it-assets-certbot
    restart: always
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  db:
    image: postgres:15-alpine
    container_name: it-assets-db
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=it_assets
    volumes:
      - pgdata-prod:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: it-assets-grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3001:3000"
    user: "0" # Run as root to avoid permission issues with volumes
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  pgdata-prod:
  grafana-data:
